demo/demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("googlemap/", include("googlemap.urls")),
    path("leaflet/", include("leaflet.urls")),
    path("mapbox/", include("mapbox.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/googlemap/urls.py
from django.urls import path
from googlemap.views import (
    InteractivePointFieldAddView,
    InteractivePointFieldEditView,
    InteractivePointFieldListView,
    StaticPointFieldEditView,
    StaticPointFieldListView,
)

app_name = "googlemap"

urlpatterns = [
    path(
        "pointfield/interactive/",
        InteractivePointFieldListView.as_view(),
        name="pointfield_interactive_list",
    ),
    path(
        "pointfield/interactive/<int:pk>/",
        InteractivePointFieldEditView.as_view(),
        name="pointfield_interactive_edit",
    ),
    path(
        "pointfield/interactive/add/",
        InteractivePointFieldAddView.as_view(),
        name="pointfield_interactive_add",
    ),
    path(
        "pointfield/static/",
        StaticPointFieldListView.as_view(),
        name="pointfield_static_list",
    ),
    path(
        "pointfield/static/<int:pk>/",
        StaticPointFieldEditView.as_view(),
        name="pointfield_static_edit",
    ),
]

demo/googlemap/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.urls import reverse

from demo.db import BaseModel

DEFAULT_LOCATION_POINT = Point(-104.9903, 39.7392)


class InteractivePointField(BaseModel):
    name = models.CharField(max_length=255)
    location = models.PointField(help_text="Use map widget to point the location")
    location_has_default = models.PointField(default=DEFAULT_LOCATION_POINT)
    location_optional = models.PointField(blank=True, null=True)

    class Meta:
        verbose_name = "Interactive PointField Widget"
        verbose_name_plural = "Interactive PointField Widget"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("googlemap:pointfield_interactive_edit", args=(self.id,))


class InteractiveInlinePointField(BaseModel):
    point = models.ForeignKey(InteractivePointField, on_delete=models.CASCADE)

    first_point = models.PointField(help_text="Use map widget to point the location")
    second_point = models.PointField(default=DEFAULT_LOCATION_POINT)


class StaticPointField(InteractivePointField):
    class Meta:
        proxy = True
        verbose_name = "Static PointField Widget"
        verbose_name_plural = "Static PointField Widget"

    def get_absolute_url(self):
        return reverse("googlemap:pointfield_static_edit", args=(self.id,))

demo/googlemap/forms.py
from django import forms
from googlemap.models import InteractivePointField, StaticPointField

from mapwidgets import GoogleMapPointFieldStaticWidget, GoogleMapPointFieldWidget


class InteractivePointFieldViewForm(forms.ModelForm):
    class Meta:
        model = InteractivePointField
        fields = ("name", "location", "location_has_default")
        widgets = {
            "location": GoogleMapPointFieldWidget,
            "location_has_default": GoogleMapPointFieldWidget(
                settings={"mapOptions": {"scrollwheel": True}}
            ),
        }


class StaticPointFieldViewForm(forms.ModelForm):
    class Meta:
        model = StaticPointField
        fields = ("name", "location", "location_has_default")
        widgets = {
            "location": GoogleMapPointFieldStaticWidget,
            "location_has_default": GoogleMapPointFieldStaticWidget(
                settings={"enableMagnificPopup": False}
            ),
        }

demo/googlemap/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView
from googlemap.forms import InteractivePointFieldViewForm, StaticPointFieldViewForm
from googlemap.models import InteractivePointField, StaticPointField


class InteractivePointFieldListView(ListView):
    queryset = InteractivePointField.objects.all().order_by("-updated_at")
    template_name = "googlemap/pointfield/interactive/list.html"
    context_object_name = "pointfield_objs"


class InteractivePointFieldEditView(UpdateView):
    form_class = InteractivePointFieldViewForm
    model = InteractivePointField
    template_name = "googlemap/pointfield/interactive/edit.html"
    context_object_name = "obj"
    success_url = reverse_lazy("googlemap:pointfield_interactive_list")


class InteractivePointFieldAddView(FormView):
    template_name = "googlemap/pointfield/interactive/add.html"
    form_class = InteractivePointFieldViewForm
    success_url = reverse_lazy("googlemap:pointfield_interactive_list")

    def form_valid(self, form):
        form.save()
        return super(InteractivePointFieldAddView, self).form_valid(form)


class StaticPointFieldListView(ListView):
    queryset = StaticPointField.objects.all().order_by("-updated_at")
    template_name = "googlemap/pointfield/static/list.html"
    context_object_name = "pointfield_objs"


class StaticPointFieldEditView(UpdateView):
    form_class = StaticPointFieldViewForm
    model = StaticPointField
    template_name = "googlemap/pointfield/static/edit.html"
    context_object_name = "obj"
    success_url = reverse_lazy("googlemap:pointfield_static_list")

demo/googlemap/templates/googlemap/pointfield/interactive/add.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block javascript %}
    <script type="text/javascript">
        (function ($) {
            $(document).on("googleMapPointFieldWidget:markerCreate", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_create"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("googleMapPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_change"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("googleMapPointFieldWidget:markerDelete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_delete"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })

            $(document).on("googleMapPointFieldWidget:placeChanged", function (e, place, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: place_changed"); // django widget textarea widget (hidden)
                console.log(place);
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });
            console.log($("#location-map-elem").data("mwMapObj")); // GoogleMap JS object
            console.log($("#location-map-elem").data("mwClassObj")); // the widget class instance object
        })(jQuery)
    </script>
{% endblock javascript %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "googlemap:pointfield_interactive_list" %}">Google Maps Point Field</a></li>
    <li class="breadcrumb-item">New Item</li>
{% endblock %}

{% block content %}
    <h4>Add New Item</h4>
    <form action="{% url "googlemap:pointfield_interactive_add" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
{% endblock content %}

demo/googlemap/templates/googlemap/pointfield/interactive/edit.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block javascript %}
    <script type="text/javascript">
        (function ($) {
            $(document).on("googleMapPointFieldWidget:markerCreate", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_create"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("googleMapPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_change"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("googleMapPointFieldWidget:markerDelete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_delete"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })

            $(document).on("googleMapPointFieldWidget:placeChanged", function (e, place, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: place_changed"); // django widget textarea widget (hidden)
                console.log(place);
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });
            console.log($("#id_location").data("PointFieldMapObj"));
            console.log($("#id_location").data("PointFieldClassObj"));
        })(mapWidgets.jQuery)
    </script>
{% endblock javascript %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "googlemap:pointfield_interactive_list" %}">GoogleMap PointField Interactive Widget</a></li>
{% endblock %}


{% block content %}
    <form action="{% url "googlemap:pointfield_interactive_edit" obj.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
{% endblock content %}

demo/googlemap/templates/googlemap/pointfield/interactive/list.html
{% extends "base.html" %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "googlemap:pointfield_interactive_list" %}">Google Maps Point Field</a></li>
{% endblock %}


{% block content %}
    <div style="margin-bottom: 20px"><a href="{% url "googlemap:pointfield_interactive_add" %}" class="btn btn-default block">Add New Item</a>
    </div>
    <h3>Items</h3>
    <ul class="block">
        {% for obj in pointfield_objs %}
            <li><a href="{% url "googlemap:pointfield_interactive_edit" obj.pk %}">{{ obj.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}