demo/demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("googlemap/", include("googlemap.urls")),
    path("leaflet/", include("leaflet.urls")),
    path("mapbox/", include("mapbox.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/googlemap/urls.py
from django.urls import path
from googlemap.views import (
    InteractivePointFieldAddView,
    InteractivePointFieldEditView,
    InteractivePointFieldListView,
    StaticPointFieldEditView,
    StaticPointFieldListView,
)

app_name = "googlemap"

urlpatterns = [
    path(
        "pointfield/interactive/",
        InteractivePointFieldListView.as_view(),
        name="pointfield_interactive_list",
    ),
    path(
        "pointfield/interactive/<int:pk>/",
        InteractivePointFieldEditView.as_view(),
        name="pointfield_interactive_edit",
    ),
    path(
        "pointfield/interactive/add/",
        InteractivePointFieldAddView.as_view(),
        name="pointfield_interactive_add",
    ),
    path(
        "pointfield/static/",
        StaticPointFieldListView.as_view(),
        name="pointfield_static_list",
    ),
    path(
        "pointfield/static/<int:pk>/",
        StaticPointFieldEditView.as_view(),
        name="pointfield_static_edit",
    ),
]

demo/leaflet/urls.py
from django.urls import path, re_path
from leaflet.views import PointFieldAddView, PointFieldDetailView, PointFieldListView

app_name = "leaflet"

urlpatterns = [
    re_path(r"^pointfield/$", PointFieldListView.as_view(), name="list"),
    re_path(r"^pointfield/(?P<pk>\d+)/$", PointFieldDetailView.as_view(), name="edit"),
    re_path(r"^pointfield/add/$", PointFieldAddView.as_view(), name="add"),
]

demo/mapbox/urls.py
from django.urls import path
from mapbox.views import (
    InteractivePointFieldAddView,
    InteractivePointFieldEditView,
    InteractivePointFieldListView,
    StaticPointFieldEditView,
    StaticPointFieldListView,
)

app_name = "mapbox"

urlpatterns = [
    path(
        "pointfield/interactive/",
        InteractivePointFieldListView.as_view(),
        name="pointfield_interactive_list",
    ),
    path(
        "pointfield/interactive/<int:pk>/",
        InteractivePointFieldEditView.as_view(),
        name="pointfield_interactive_edit",
    ),
    path(
        "pointfield/interactive/add/",
        InteractivePointFieldAddView.as_view(),
        name="pointfield_interactive_add",
    ),
    path(
        "pointfield/static/",
        StaticPointFieldListView.as_view(),
        name="pointfield_static_list",
    ),
    path(
        "pointfield/static/<int:pk>/",
        StaticPointFieldEditView.as_view(),
        name="pointfield_static_edit",
    ),
]

demo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block blockbots %}
        <meta name="robots" content="NONE,NOARCHIVE"/>{% endblock %}
    <title>Django Map Widgets - Demo</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
    <script type="text/javascript" src="{% static "js/jquery-3.7.1.slim.min.js" %}"></script>
    {% block extrahead %}
    {% endblock extrahead %}
</head>
<body>
<div class="container help-block pb-5 pt-2">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url "index" %}">MapWidgets Demo</a></li>
            {% block breadcrumb_item %}
            {% endblock %}
            {% if obj %}
                <li class="breadcrumb-item"><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a></li>
            {% endif %}
        </ol>
    </nav>
    {% block content %}
    {% endblock content %}
</div>

{% block javascript %}
{% endblock javascript %}

</body>
</html>

demo/templates/index.html
{% extends "base.html" %}


{% block content %}
    <div class="row container">
        <h3 class="text-black" style="margin-bottom: 40px; padding: 0">Map Widgets</h3>
        <div class="col-md-6">
            <h4>Interactive Widgets</h4>
            <ul>
                <li><a href="{% url "googlemap:pointfield_interactive_list" %}">GoogleMap PointField Interactive
                    Widget</a></li>
                <li><a href="{% url "leaflet:list" %}">Leaflet PointField Interactive Widget</a></li>
                <li><a href="{% url "mapbox:pointfield_interactive_list" %}">Mapbox Map PointField Interactive
                    Widget</a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <h4>Static Widgets</h4>
            <ul>
                <li><a href="{% url "googlemap:pointfield_static_list" %}">GoogleMap PointField Static Widget</a></li>
                <li><a href="{% url "mapbox:pointfield_static_list" %}">Mapbox PointField Static Widget</a></li>
            </ul>
        </div>
    </div>

{% endblock content %}