demo/demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("googlemap/", include("googlemap.urls")),
    path("leaflet/", include("leaflet.urls")),
    path("mapbox/", include("mapbox.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/mapbox/urls.py
from django.urls import path
from mapbox.views import (
    InteractivePointFieldAddView,
    InteractivePointFieldEditView,
    InteractivePointFieldListView,
    StaticPointFieldEditView,
    StaticPointFieldListView,
)

app_name = "mapbox"

urlpatterns = [
    path(
        "pointfield/interactive/",
        InteractivePointFieldListView.as_view(),
        name="pointfield_interactive_list",
    ),
    path(
        "pointfield/interactive/<int:pk>/",
        InteractivePointFieldEditView.as_view(),
        name="pointfield_interactive_edit",
    ),
    path(
        "pointfield/interactive/add/",
        InteractivePointFieldAddView.as_view(),
        name="pointfield_interactive_add",
    ),
    path(
        "pointfield/static/",
        StaticPointFieldListView.as_view(),
        name="pointfield_static_list",
    ),
    path(
        "pointfield/static/<int:pk>/",
        StaticPointFieldEditView.as_view(),
        name="pointfield_static_edit",
    ),
]

demo/mapbox/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.urls import reverse

from demo.db import BaseModel

DEFAULT_LOCATION_POINT = Point(-104.8803, 39.7392)


class InteractivePointField(BaseModel):
    name = models.CharField(max_length=255)
    location = models.PointField(help_text="Use map widget to point the location")
    location_has_default = models.PointField(default=DEFAULT_LOCATION_POINT)
    location_optional = models.PointField(blank=True, null=True)

    class Meta:
        verbose_name = "Interactive PointField Widget"
        verbose_name_plural = "Interactive PointField Widget"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("mapbox:pointfield_interactive_edit", args=(self.id,))


class StaticPointField(InteractivePointField):
    class Meta:
        proxy = True
        verbose_name = "Static PointField Widget"
        verbose_name_plural = "Static PointField Widget"

    def get_absolute_url(self):
        return reverse("mapbox:pointfield_static_edit", args=(self.id,))

demo/mapbox/forms.py
from django import forms
from mapbox.models import InteractivePointField, StaticPointField

from mapwidgets import MapboxPointFieldStaticWidget, MapboxPointFieldWidget


class InteractivePointFieldViewForm(forms.ModelForm):
    class Meta:
        model = InteractivePointField
        fields = ("name", "location")
        widgets = {
            "location": MapboxPointFieldWidget,
        }


class StaticPointFieldViewForm(forms.ModelForm):
    class Meta:
        model = StaticPointField
        fields = ("name", "location", "location_has_default")
        widgets = {
            "location": MapboxPointFieldStaticWidget,
            "location_has_default": MapboxPointFieldStaticWidget(
                settings={"enableMagnificPopup": False}
            ),
        }

demo/mapbox/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView
from mapbox.forms import InteractivePointFieldViewForm, StaticPointFieldViewForm
from mapbox.models import InteractivePointField, StaticPointField


class InteractivePointFieldListView(ListView):
    queryset = InteractivePointField.objects.all().order_by("-updated_at")
    template_name = "mapbox/pointfield/interactive/list.html"
    context_object_name = "pointfield_objs"


class InteractivePointFieldEditView(UpdateView):
    form_class = InteractivePointFieldViewForm
    model = InteractivePointField
    template_name = "mapbox/pointfield/interactive/edit.html"
    context_object_name = "obj"
    success_url = reverse_lazy("mapbox:pointfield_interactive_list")


class InteractivePointFieldAddView(FormView):
    template_name = "mapbox/pointfield/interactive/add.html"
    form_class = InteractivePointFieldViewForm
    success_url = reverse_lazy("mapbox:list")

    def form_valid(self, form):
        form.save()
        return super(InteractivePointFieldAddView, self).form_valid(form)


class StaticPointFieldListView(ListView):
    queryset = StaticPointField.objects.all().order_by("-updated_at")
    template_name = "mapbox/pointfield/static/list.html"
    context_object_name = "pointfield_objs"


class StaticPointFieldEditView(UpdateView):
    form_class = StaticPointFieldViewForm
    model = StaticPointField
    template_name = "mapbox/pointfield/static/edit.html"
    context_object_name = "obj"
    success_url = reverse_lazy("mapbox:pointfield_static_list")

demo/mapbox/templates/mapbox/pointfield/interactive/add.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block javascript %}
    <script type="text/javascript">
        (function ($) {
            $(document).on("mapboxPointFieldWidget:markerCreate", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_create"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("mapboxPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_change"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("mapboxPointFieldWidget:markerDelete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_delete"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })

            $(document).on("mapboxPointFieldWidget:placeChanged", function (e, place, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: place_changed"); // django widget textarea widget (hidden)
                console.log(place);
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });
            console.log($("#id_location").data("PointFieldMapObj"));
            console.log($("#id_location").data("PointFieldClassObj"));
        })(jQuery)
    </script>
{% endblock javascript %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "mapbox:pointfield_interactive_list" %}">Mapbox Point Field</a></li>
    <li class="breadcrumb-item">New Item</li>
{% endblock %}


{% block content %}
    <h4>Add New Item</h4>
    <form action="{% url "mapbox:pointfield_interactive_add" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
{% endblock content %}

demo/mapbox/templates/mapbox/pointfield/interactive/edit.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block javascript %}
    <script type="text/javascript">
        (function ($) {
            $(document).on("mapboxPointFieldWidget:markerCreate", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_create"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("mapboxPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_change"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("mapboxPointFieldWidget:markerDelete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_delete"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })

            $(document).on("mapboxPointFieldWidget:placeChanged", function (e, place, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: place_changed"); // django widget textarea widget (hidden)
                console.log(place);
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });
            console.log($("#id_location").data("PointFieldMapObj"));
            console.log($("#id_location").data("PointFieldClassObj"));
        })(jQuery)
    </script>
{% endblock javascript %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "mapbox:pointfield_interactive_list" %}">Mapbox Point Field</a></li>
{% endblock %}

{% block content %}
    <h4>{{ obj.name }}</h4>
    <form action="{% url "mapbox:pointfield_interactive_edit" obj.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
{% endblock content %}

demo/mapbox/templates/mapbox/pointfield/interactive/list.html
{% extends "base.html" %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "mapbox:pointfield_interactive_list" %}">Mapbox Point Field</a></li>
{% endblock %}

{% block content %}
    <div style="margin-bottom: 20px"><a href="{% url "mapbox:pointfield_interactive_add" %}" class="btn btn-default block">Add New Item</a>
    </div>
    <h3>Items</h3>
    <ul class="block">
        {% for obj in pointfield_objs %}
            <li><a href="{% url "mapbox:pointfield_interactive_edit" obj.pk %}">{{ obj.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}