demo/demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("googlemap/", include("googlemap.urls")),
    path("leaflet/", include("leaflet.urls")),
    path("mapbox/", include("mapbox.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo/leaflet/urls.py
from django.urls import path, re_path
from leaflet.views import PointFieldAddView, PointFieldDetailView, PointFieldListView

app_name = "leaflet"

urlpatterns = [
    re_path(r"^pointfield/$", PointFieldListView.as_view(), name="list"),
    re_path(r"^pointfield/(?P<pk>\d+)/$", PointFieldDetailView.as_view(), name="edit"),
    re_path(r"^pointfield/add/$", PointFieldAddView.as_view(), name="add"),
]

demo/leaflet/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.urls import reverse

from demo.db import BaseModel

DEFAULT_LOCATION_POINT = Point(-104.7703, 39.7392)


class InteractivePointField(BaseModel):
    name = models.CharField(max_length=255)
    location = models.PointField(help_text="Use map widget to point the location")
    location_has_default = models.PointField(default=DEFAULT_LOCATION_POINT)
    location_optional = models.PointField(blank=True, null=True)

    class Meta:
        verbose_name = "Interactive PointField Widget"
        verbose_name_plural = "Interactive PointField Widgets"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("leaflet:edit", args=(self.id,))

demo/leaflet/forms.py
from django import forms
from leaflet.models import InteractivePointField

from mapwidgets import LeafletPointFieldWidget


class InteractivePointFieldViewForm(forms.ModelForm):
    class Meta:
        model = InteractivePointField
        fields = ("name", "location")
        widgets = {
            "location": LeafletPointFieldWidget,
        }

demo/leaflet/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView
from leaflet.forms import InteractivePointFieldViewForm
from leaflet.models import InteractivePointField


class PointFieldListView(ListView):
    queryset = InteractivePointField.objects.all().order_by("-updated_at")
    template_name = "leaflet/pointfield/list.html"
    context_object_name = "pointfield_objs"


class PointFieldDetailView(UpdateView):
    form_class = InteractivePointFieldViewForm
    model = InteractivePointField
    template_name = "leaflet/pointfield/edit.html"
    context_object_name = "obj"
    success_url = reverse_lazy("leaflet:list")


class PointFieldAddView(FormView):
    template_name = "leaflet/pointfield/add.html"
    form_class = InteractivePointFieldViewForm
    success_url = reverse_lazy("leaflet:list")

    def form_valid(self, form):
        form.save()
        return super(PointFieldAddView, self).form_valid(form)

demo/leaflet/templates/leaflet/pointfield/add.html
{% extends "base.html" %}

{% block javascript %}
    <script type="text/javascript">
        (function ($) {
            $(document).on("leafletPointFieldWidget:markerCreate", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_create"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("leafletPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_change"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("leafletPointFieldWidget:markerDelete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_delete"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })

            $(document).on("leafletPointFieldWidget:placeChanged", function (e, place, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: place_changed"); // django widget textarea widget (hidden)
                console.log(place);
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });
            console.log($("#id_location").data("PointFieldMapObj"));
            console.log($("#id_location").data("PointFieldClassObj"));
        })(jQuery)
    </script>
{% endblock javascript %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "leaflet:list" %}">Leaflet Point Field</a></li>
    <li  class="breadcrumb-item">New Item</li>
{% endblock %}


{% block content %}
    <h4>Add New Item</h4>
    <form action="{% url "leaflet:add" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
{% endblock content %}

demo/leaflet/templates/leaflet/pointfield/edit.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "leaflet:list" %}">Leaflet Point Field</a></li>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        (function ($) {
            $(document).on("leafletPointFieldWidget:markerCreate", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_create"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("leafletPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_change"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("leafletPointFieldWidget:markerDelete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: marker_delete"); // django widget textarea widget (hidden)
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })

            $(document).on("leafletPointFieldWidget:placeChanged", function (e, place, lat, lng, locationInputElem, mapWrapID) {
                console.log("EVENT: place_changed"); // django widget textarea widget (hidden)
                console.log(place);
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });
            console.log($("#id_location").data("PointFieldMapObj"));
            console.log($("#id_location").data("PointFieldClassObj"));
        })(jQuery)
    </script>
{% endblock javascript %}


{% block content %}
    <h4>{{ obj.name }}</h4>
    <form action="{% url "leaflet:edit" obj.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
{% endblock content %}

demo/leaflet/templates/leaflet/pointfield/list.html
{% extends "base.html" %}

{% block breadcrumb_item %}
    <li class="breadcrumb-item"><a href="{% url "leaflet:list" %}">Leaflet Point Field</a></li>
{% endblock %}

{% block content %}
    <div style="margin-bottom: 20px"><a href="{% url "leaflet:add" %}" class="btn btn-default block">Add New Item</a>
    </div>
    <h3>Items</h3>
    <ul class="block">
        {% for obj in pointfield_objs %}
            <li><a href="{% url "leaflet:edit" obj.pk %}">{{ obj.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}